= Teamplanning (Java, Quarkus, Maven)

[[req]]
== Requirements
* Java
* Mariadb
* Maven

Bewerk template (app.template) naar vereisten en schrijf naar:

[source, shell]
/src/main/resources/application.properties

[[run]]
== Starten van de applicatie met Maven

. Git clone:
+
[source, shell]
----
$ git clone https://github.com/zwarenelle/archangel.git
----

. Start de applicatie met Maven:
+
[source, shell]
----
$ mvn quarkus:dev
----

. Open http://localhost:8080 in een browser.

. Kies *Solve* om het planningsprobleem op te lossen.

Probeer dan _live coderen_:

. Pas de source code aan.
. Ververs de browser (F5).

De wijzigingen worden meteen zichtbaar.

= Verdere mogelijkheden

[[package]]
== Run the packaged application

When you're done iterating in `quarkus:dev` mode,
package the application to run as a conventional jar file.

. Compile it with Maven:
+
[source, shell]
----
$ mvn package
----

. Run it:
+
[source, shell]
----
$ java -jar ./target/quarkus-app/quarkus-run.jar
----
+
[NOTE]
====
To run it on port 8081 instead, add `-Dquarkus.http.port=8081`.
====

. Visit http://localhost:8080 in your browser.

. Click on the *Solve* button.

[[container]]
== Run the application in a container

. Build a container image:
+
[source, shell]
----
$ mvn package -Dcontainer
----
The container image name
. Run a container:
+
[source, shell]
----
$ docker run -p 8080:8080 timefold-solver-quarkus-maintenance-scheduling-quickstart:1.0-SNAPSHOT
----

[[native]]
== Run it native

To increase startup performance for serverless deployments,
build the application as a native executable:

. https://quarkus.io/guides/building-native-image#configuring-graalvm[Install GraalVM and gu install the native-image tool]

. Compile it natively. This takes a few minutes:
+
[source, shell]
----
$ mvn package -Dnative -DskipTests
----

. Run a database. By default, `application.properties` is configured for H2:
.. Download the http://www.h2database.com/html/download.html[H2 database] (Platform-independent zip) and unzip it.
.. Start the H2 server with the option `-ifNotExists` (not recommended in production):
+
[source, shell]
----
$ cd h2/bin
$ java -cp h2*.jar org.h2.tools.Server -ifNotExists
----

. Run the native executable:
+
[source, shell]
----
$ ./target/*-runner
----

. Visit http://localhost:8080 in your browser.

. Click on the *Solve* button.